title: "roller-epi"
description: "Executor Plugin Interface Documentation"
baseurl: "/roller-epi"
url: "https://laplasd.github.io/roller-epi/" # Адрес сайта

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

navigation:
  - name: "Home"
    link: "/"
  - name: "About"
    link: "/about"
