title: "roller-epi"
description: "Documentation and pages"
baseurl: "/roller-epi"
url: "https://laplasd.github.io/roller-epi/" # Адрес сайта
theme: minima

navigation:
  - name: "Home"
    link: "/"
  - name: "About"
    link: "/about"
